//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aoc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aoc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15560
        ///3906
        ///7076
        ///11980
        ///11508
        ///
        ///6558
        ///2256
        ///7294
        ///6566
        ///2686
        ///2566
        ///1724
        ///4811
        ///5427
        ///4278
        ///3756
        ///
        ///3761
        ///5599
        ///13187
        ///12558
        ///7425
        ///9269
        ///
        ///59658
        ///
        ///34175
        ///9643
        ///
        ///7664
        ///10224
        ///5541
        ///1378
        ///1784
        ///9347
        ///7692
        ///
        ///3786
        ///4260
        ///4416
        ///6345
        ///6750
        ///6415
        ///5467
        ///4898
        ///2017
        ///4486
        ///1198
        ///1960
        ///
        ///5658
        ///6168
        ///8088
        ///7749
        ///5890
        ///1980
        ///6014
        ///1136
        ///3138
        ///6706
        ///7041
        ///
        ///9197
        ///6997
        ///12644
        ///12609
        ///7630
        ///12928
        ///
        ///5278
        ///1423
        ///4822
        ///5148
        ///6387
        ///1280
        ///6431
        ///3847
        ///5886
        ///2714
        ///3725
        ///6331
        ///
        ///7537
        ///6965
        ///10079
        ///8904
        ///8639
        ///10679
        ///8964        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day1 {
            get {
                return ResourceManager.GetString("input_day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Y
        ///A Y
        ///B X
        ///A Y
        ///C Y
        ///B Y
        ///B Z
        ///B Y
        ///A X
        ///B X
        ///C Z
        ///B Y
        ///B Y
        ///B Y
        ///B Y
        ///C X
        ///A Z
        ///B X
        ///A Y
        ///A Y
        ///B Y
        ///A X
        ///C X
        ///B Y
        ///A Y
        ///B Y
        ///C X
        ///A Z
        ///B Y
        ///A X
        ///A Y
        ///B Y
        ///A Y
        ///A X
        ///B Y
        ///B Y
        ///B Y
        ///B X
        ///A X
        ///C Y
        ///A X
        ///C Z
        ///B Z
        ///A Z
        ///A Z
        ///C X
        ///A X
        ///A X
        ///B Y
        ///B Y
        ///C Y
        ///B Y
        ///B X
        ///B Y
        ///B Y
        ///B X
        ///C X
        ///A X
        ///A X
        ///A Z
        ///C X
        ///A Z
        ///A X
        ///B Y
        ///B Y
        ///A Y
        ///A Z
        ///B Y
        ///B X
        ///B Y
        ///B Y
        ///B X
        ///C Z
        ///A X
        ///B X
        ///B X
        ///A Y
        ///B X
        ///C Z
        ///B Y
        ///A X
        ///C Z
        ///A Y
        ///B Y
        ///B Y
        ///A X
        ///A Z
        ///B Y
        ///B Y
        ///A Z
        ///A Z
        ///B Y
        ///A X
        ///A Z
        ///C Y
        ///A X
        ///B Y
        ///C X
        ///A X
        ///B Y
        ///A X
        ///A Z
        ///C X
        ///A Y
        ///A X
        ///B X
        ///A X
        ///B Z
        ///B X
        ///B Y
        ///A X
        ///A Y
        ///B Y
        ///B Z
        ///C X
        ///B X
        ///A X
        ///C Z
        ///C Y
        ///A Y
        ///B Y
        ///A X
        ///B Y
        ///C Y
        ///B Y
        ///C Y
        ///B Y
        ///C Z
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_day2 {
            get {
                return ResourceManager.GetString("input_day2", resourceCulture);
            }
        }
    }
}
